version: "3.8"
services:
  database:
    image: mysql/mysql-server:8.0.26
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: EDUCATION